name: documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test Build
        run: |
          yarn install --frozen-lockfile
          yarn build

  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test Build
        run: |
          yarn install --frozen-lockfile
          yarn docs-sync pull OSS-Docs-Tools/example-localization-repo#main 0
          yarn build

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: "gh-pages"
          PUBLISH_DIR: ./build
